spring:
  cloud:
#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        endpoint: oss-cn-chengdu.aliyuncs.com
#        bucket: gulimall-snowcying
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-third-party
server:
  port: 30000
